name: Build and deploy ASP.Net Core BotHost to Azure Web App - uzjonlichat

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Build BotHost
        run: dotnet build UzJonliChatBot.BotHost/UzJonliChatBot.BotHost.csproj -c Release

      - name: Publish BotHost
        run: dotnet publish UzJonliChatBot.BotHost/UzJonliChatBot.BotHost.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: bothost-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: bothost-app
      

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5D351181ACC7429FB40D3F4487019BF1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_49C74F06A617460B96EE4847E1C8174D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3E566B2B875A4B588F447A5E93E8F216 }}

      - name: Deploy BotHost to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'uzjonlichat'
          slot-name: 'Production'
          # Use the artifact folder downloaded by the previous step
          # download-artifact extracts the artifact into a folder named after the artifact (bothost-app)
          package: ${{ github.workspace }}/bothost-app
